name: HR Payroll Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Create directories
        run: |
          mkdir -p reports/extent
          mkdir -p reports/html
          mkdir -p reports/json
          mkdir -p screenshots
          mkdir -p logs

      - name: Run tests with clean Maven settings
        env:
          MAVEN_OPTS: "-Dmaven.repo.local=$HOME/.m2/repository"
        run: |
          mvn --batch-mode --update-snapshots \
          clean test \
          -Dtest=SmokeTestRunner \
          -Dbrowser=chrome \
          -Dheadless=true \
          -Dmaven.test.failure.ignore=true \
          -Dsettings.security=/dev/null

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/surefire-reports/
            reports/
            screenshots/
          retention-days: 7
