name: HR Payroll Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  MAVEN_OPTS: -Xmx1024m

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome]
        test-suite: [SmokeTestRunner]
        
    name: Test ${{ matrix.test-suite }} on ${{ matrix.browser }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Install Chrome and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable xvfb
        
    - name: Create directories
      run: |
        mkdir -p reports/extent
        mkdir -p screenshots
        mkdir -p logs
        
    - name: Run tests
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        mvn clean test \
          -Dtest=${{ matrix.test-suite }} \
          -Dbrowser=${{ matrix.browser }} \
          -Dheadless=true \
          -Dmaven.test.failure.ignore=true
          
    - name: Debug - List generated files
      if: always()
      run: |
        echo "=== Project structure ==="
        ls -la
        echo "=== Target directory ==="
        ls -la target/ || echo "No target directory"
        echo "=== Surefire reports ==="
        ls -la target/surefire-reports/ || echo "No surefire-reports"
        echo "=== Reports ==="
        ls -la reports/ || echo "No reports directory"
        
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.browser }}
        path: |
          target/surefire-reports/
          reports/
          screenshots/
          logs/
        retention-days: 7